# 2017 

## Tentti 

Yksi esseekysymys sama kuin tulevina vuosina (päänsäryn vaaran merkit).

### Polyneuropatia 

- a. Polyneuropatian syyt ja kliininen kuva
- b. Kivuliaan polyneuropatian hoito

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Polyneuropatioille on useita eri syitä (geneettiset, immunologiset, hankinnaiset…), mutta kattavien tutkimustenkin jälkeen etiologia jää epäselväksi n. 1/3 polyneuropatiatapauksista. 

Yleisimmät kaksi syytä ovat diabetes ja alkoholi. Muita ovat mm. B12-vitamiinin puutos, hypotyreoosi, maksan/munuaisten vajaatoiminta, B6-toksisuus, sytostaatit/muut lääkkeet...

Yleisin perinnöllinen polyneuropatia on Charcot-Marie-Toothin (CMT) tauti (hereditaarinen motosensorinen neuropatia (HMSN). CMT:stä on monia eri tyyppejä, mutta alkavat useimmiten n. 5-25-vuotiaana ja yleisin periytymistapa on autosomissa vallitsevasti. 

Periaatteessa myös polyradikuliitit (Guillain-Barrén oireyhtymä ja CIDP) voidaan laskea polyneuropatioihin. Ne ovat autoimmuunisairauksia. 

---

Polyneuropatiat voivat affisioida sensorisia hermoja, motorisia hermoja ja/tai autonomisia hermoja ja täten aiheuttaa monia erilaisia oireita. Sensoriset oireet voidaan luokitella "negatiivisiin" ja "positiivisiin". Negatiivisilla oireilla tarkoitetaan tunnon heikentymistä tai puuttumista. Positiivisilla oireilla tarkoitetaan lisääntyneitä tai muuttuneita ihon tunto-oireita (esimerkiksi pistely, kihelmöinti, polttelu sekä allodynia, jossa ei-kivulias stimulus koetaan kipuna, sekä hyperalgesia, jossa kipuaistimus koetaan liiallisena; hermokivut ovat yleensä pahimmillaan ilta- ja yöaikaan eli levossa). Useimmiten oirekuva on symmetrinen ja alkaa yleensä hermojen distaaliosissa ja leviää vähitellen proksimaalisesti. Tyypillisin ensioire on siis sukka- ja hansikasmainen tuntopuutos raajojen kärkijäsenissä, usein alkaen alaraajoista. Jalkapohjien tuntopuutokset johtavat helposti tasapainovaikeuksiin ja kävelyn heikentymiseen. Statuksessa kosketustunnon heikkeneminen (monofilamenttikoe), värinätunnon häviäminen (ääniraudalla) sekä akillesheijasteen puuttuminen ovat herkimmät alaraajojen neuropatian kliiniset osoittajat. Mittaavat paksujen hermosäikeiden toimintaa. Ohutsäieneuropatian diagnoosi perustuu pitkälti tyypillisiin oireisiin (kipu, lämpötilan erotuskyky alentunut), mutta haastavissa tapauksissa voidaan tutkia QST, ihobiopsia tai CHEP.

Motoristen hermojen affisioituminen johtaa lihasheikkouteen, -atrofiaan, -kouristuksiin tai vapinaan. Jännevenytysheijasteet heikentyvät ja lihasheikkouksia voi esiintyä; babinskit negatiiviset. Motoriset ongelmat voivat tuntopuutosten kanssa aiheuttaa rakenteellisia muutoksia, kuten korkeita jalkaholveja ja vasaravarpaita. 

Autonominen neuropatia voi aiheuttaa mm. GI-oireita (esim. ummetus ja gastropareesi), rakon tyhjenemisongelmia, verenkierrollisia ongelmia (esim. ortostatismi) ja hikoiluhäiriöitä (ja aiheuttaa jaloissa mm. kuivumia ja halkeamia -> altistaa infektioille).
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Etiologian ja taustasairauden mukainen hoito on tärkeää (esim. diabeteksen hoitotasapaino, alkoholin käytön vähentäminen, B12-lisä yms). Kuntoutus, apuvälineet ja jalkahoito ovat yleisesti käytettyjä tukitoimia. 

Kivun lääkehoito on tyypillistä neuropaattisen kivun hoitoa; käytössä siis trisykliset masennuslääkkeet (nortriptyliini, amitriptyliini), SNRI-lääkkeet (duloksetiini, venlafaksiini) ja gabapentinoidit (gabapentiini, pregabaliini). Joskus harvoin voidaan käyttää heikkoja opioideja lyhytaikaisesti.
  </div>
</div>

### Toistuvat tajunnanmenetykset 

- a. syyt 
- b. tarvittavat tutkimukset; keskity tutkimuksissa erotusdiagnostiikkaan

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Tajunnanmenetyksen (ei siis jatkuvan tajuttomuuden; siihen VOI IHME!) syyt voi jakaa periaatteessa kolmeen pääryhmään: synkopee, epileptiset kohtaukset ja muut. 

---

Synkopee voidaan edelleen jakaa kolmeen pääryhmään: heijasteperäinen (yleensä vasovagaalinen), ortostaattinen ja sydänperäinen. 

<li>Vasovagaalinen synkopee on yleisin; pelko, kipu, pitkä seisominen laukaisee vagushermon kautta ääreisvastuksen heikkenemisen ja/tai sykkeen hidastumisen ja sitä kautta globaalin hypoperfuusion aivoissa -> synkopee</li>
<li>Ortostaattinen johtuu verenpaineen tippumisesta asentoa muuttaessa (esim. makuulta seisomaan); Syynä usein lääkitys, kuivuminen, autonomisen hermoston häiriö, ikääntyminen</li>
<li>Kardiogeeninen on vaarallisin ja johtuu esim. rytmihäiriöistä tai aorttastenoosista (rasituksessa)</li>

---

Epileptiset kohtaukset 

<li>Aivojen epänormaali sähköinen purkaustoiminta. Kyseessä voi olla yleistynyt kohtaus tai paikallisalkuinen tajuntaa hämärtävä kohtaus</li>
<li>Taustalla voi olla monia sekundaarisia tekijöitä (esim. AVH, enkefaliitti, trauma, autoimmuunienkefaliitti, metaboliset syyt (esim. hypoglykemia, elektrolyyttihäiriöt), intoksikaatiot/Vieroitukset (esim. alkoholi tai bentsot), CNS-tuumori) tai kyseessä voi olla primaari epileptinen kohtaus (ei altistetta)</li>

---

Muut, kuten 

<li>Psykogeeniset kohtaukset ja simulaatiot</li>
<li>Hypoglykemiat</li>
<li>AVH:t harvemmin aiheuttavat tajuttomuutta, mutta kuitenkin mahdollista</li>
<li>Toistuvat pään traumat</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Kaikkein tärkeintä on saada anamneesi ja kohtauskuvaus tajunnanmenetyksistä. Tulee siis selvittää tuntemukset, oireet ja tilanne ennen kohtausta, kohtauksen aikana ja kohtauksen jälkeen. Potilas ei usein pysty näitä kuvaamaan (ainakaan kohtauksen aikaista), joten silminnäkijähaastattelu on äärimmäisen tärkeä. 

<li>Kuvaus kohtauksen alusta, kulusta ja jälkioireista auttaa erityisesti selvittämään, onko kyseessä oikeasti ollut epileptinen kohtaus vai enemmänkin esim. synkopee</li>
  <ul>
    <li>Esioireet: Epileptisessä kohtauksessa eniten aistioireita (esim. outo hajukokemus) ja psyykkisiä oireita; Synkopeessa tyypillisintä pahoinvointi, kalpeus, hikoilu, heikotus ja/tai näön hämärtyminen</li>
    <li>Kaatumisenaikainen lihastonus: Epileptisessä kohtauksessa yleensä tooninen, synkopeessä yleensä atooninen</li>
    <li>Lihasnykäysten määrä: Epileptisessä kohtauksessa rytmisiä, voimakkaita ja voivat jatkua pidempään; Synkopeessa lyhyitä, epäsäännöllisiä ja niitä on vähän (usein alle 10 nykäystä; on olemassa ns. 10/20 rule eli <10 nykäystä viittaa synkopeehen ja >20 epileptiseen kohtaukseen). Nykiminen alkaa synkopeessa vasta, kun henkilö on jo veltostunut ja kaatunut; epileptisessä kohtauksessa kohtaus yleensä alkaa heti kouristuksella</li>
    <li>Kesto: Synkopee yleensä lyhytkestoisempi (n. 3-30s), epileptinen kohtaus yleensä vähän pidempi (30s-pari minuuttia)</li>
    <li>Kielen purenta: Epileptisessä kohtauksessa yleisempää ja voi olla lateraalisestikin; synkopeessa korkeintaan kielen kärjen purenta</li>
    <li>Silmien avonaisuus: Epileptisessä kohtauksessa usein auki, synkopeessa yleensä kiinni</li>
    <li>Inkontinenssi: Yleisempää epileptisessä kohtauksessa</li>
  </ul>
<li>Auttaa myös jo alustavasti selvittämään kohtaustyyppiä (paikallisalkuinen/suoraan yleistynyt)</li>

---

Toiminnallisten kohtausten (ei epileptistä sähköistä aktiivisuutta; taustalla psykologinen mekanismi; potilaat eivät teeskentele oireitaan) erot epilepsiaan ovat myös usein kohtauskuvauksen perusteella selviteltävissä. Oireiston alkua edeltää useimmiten akuutti tai pitkäkestoinen poikkeuksellinen psykososiaalinen stressi.

<li>Toiminnallinen kohtaus on yleensä pitkäkestoisempi</li>
<li>Toiminnallisessa kohtauksessa silmät ovat yleensä kiinni</li>
<li>Toiminnallisessa kohtauksessa voidaan saada ulkoisesti vaikutettua oireeseen; esim. puhe- tai muun vaasteen saaminen (yllättävälle) ärsykkeelle</li>
<li>Toiminnallisessa kohtauksessa on kohtauskuvauksen vaihtelua/monimuotoisuutta kerrasta toiseen. Epilepsiassa taas usein stereotyyppisiä henkilölle itselleen </li>
<li>Toiminnallisessa kohtauksessa ei yleensä post-iktaalista sekavuutta ja toipuminen on nopeaa</li>
<li>Toiminnallisessa kohtauksessa esiintyy usein muistikuvia kohtauksesta</li>
<li>Toiminnallisessa kohtauksessa pään kääntely puolelta toiselle on yleistä</li>


---

Taustoista on tärkeää selvittää aiempi epilepsia, pään vammat, aikaisemmat AVH:t, alkoholin/päihteiden käyttö, lääkitys yms. altistavat tekijät, kuten sukurasite ja äärimmäiset rasitustilat: paasto, teräsmieskisat, pitkäaikainen valvominen. Myös muut sairaudet tulee selvittää.

<li>Jos tiedossa on jo epilepsia, niin pään kuvantaminen ei ole yhtä tärkeää kuin ensikouristajilla</li>
<li>Onko potilaan lähistöltä löydetty lääkepurkkeja tyhjänä -> ohjaa ajattelua yliannostukseen</li>
<li>Altistavat tekijät ohjaavat jatkoselvittelyitä ja vaikutuksia diagnoosiin; ei siis ole sinänsä epilepsia kyseessä, jos kohtaus liittyy johonkin välittömään ja poikkeukselliseen altistavaan tekijään (akuuttiin aivovammaan, aivosairauteen, tai systeemiseen häiriöön) ja jos altistava tekijä voidaan poistaa tai hoitaa muutoin. Altisteisena kohtauksena pidetään 7 vrk kuluessa akuutista aivotapahtumasta esiintynyttä epileptistä kohtausta</li>

---

Statuksessa: 

<li>Yleisstatus: Pään ja niskan alueen palpaatio (trauman merkit), auskultaatio (infektiot ja sydämen toiminta), ihon kunto (infektiot, traumat), </li>
<li>Suu ja kieli (puremat)</li>
<li>Kattava neurologinen status</li>

---

EKG, verenpaine kaikille. Synkopee-epäilyssä ortostaattinen koe mahdollisesti. UKG tarvittaessa ja muutenkin kardiovaskulaarinen arvio, varsinkin jos synkopee-epäily.

Jos tänään kouristellut, niin päivystykseen (ensikouristajat päivystykseen, jossa pään TT). Päivystyksessä myös labrat (a-astrup, glukoosi, PVK, elektrolyytit, Krea, ALAT, CK, TSH, CRP; troponiinit harkitusti ja päihdekäyttöä epäiltäessä puhallus, PEth, U-huumeet). Jos potilas on tullut vasta myöhempinä päivinä vastaanotolle, niin epileptisiä kohtauksia epäiltäessä neurologialle kiireellinen lähete, siellä MRI ja EEG. 

CNS-infektioepäilyssä (esim. potilaalla korkea kuume) likvor. 
  </div>
</div>

### Parkinsonin taudin neljä pääoiretta ja niiden erotusdiagnostiikka

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

  </div>
</div>

### Aivoinfarktipotilaan komplikaatioiden esto ja hoito AVH-yksikössä